name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: push code to server
      run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.PRODPK }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan ${{ secrets.PRODIP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          rsync -a --chmod=D2775,F664 "$GITHUB_WORKSPACE"/dist/ ${{ secrets.PRODUSER }}@${{ secrets.PRODIP }}:${{ secrets.PRODPATH }}
