# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Pre-auth ci user and run sync
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ProdPK }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan 207.154.220.86 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        rsync -a --chmod=D2775,F664 --delete "$GITHUB_WORKSPACE"/build/ cidelivery@207.154.220.86:/var/www/projects/angleto.agency/lab 
        
